image: maven:latest
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -U"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_REPO_PASS: $MAVEN_REPO_PASS
  MAVEN_REPO_USER: $MAVEN_REPO_USER
cache:
  paths:
    - .m2/repository/
    - target/
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  allow_failure: true
deploy:
  stage: deploy
  script:
    - echo mvn -DMAVEN_REPO_USER=$MAVEN_REPO_USER -DMAVEN_REPO_PASS=$MAVEN_REPO_PASS  $MAVEN_CLI_OPTS -DskipTests=true deploy
    - mvn -DMAVEN_REPO_USER=$MAVEN_REPO_USER -DMAVEN_REPO_PASS=$MAVEN_REPO_PASS  $MAVEN_CLI_OPTS -DskipTests=true deploy
  only:
    - master
